alter table "public"."household_members" drop constraint "household_members_member_id_fkey1";

alter table "public"."profiles" drop constraint "profiles_oauth_id_fkey";

alter table "public"."household_items" drop constraint "household_items_last_updated_by_fkey";

alter table "public"."households" drop constraint "households_creator_id_fkey";

drop index if exists "public"."household_members_household_id_member_id_idx";

alter table "public"."household_items" drop column "name";

alter table "public"."household_items" add column "title" text not null;

alter table "public"."household_items" alter column "id" drop default;

alter table "public"."household_items" alter column "id" set not null;

alter table "public"."household_items" alter column "id" add generated by default as identity;

alter table "public"."household_items" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."household_members" drop column "created_at";

alter table "public"."household_members" drop column "role";

alter table "public"."household_members" add column "joined_at" timestamp with time zone not null default now();

alter table "public"."household_members" add column "member_role" "MEMBER_ROLE" not null;

alter table "public"."household_members" alter column "id" drop default;

alter table "public"."household_members" alter column "id" add generated by default as identity;

alter table "public"."household_members" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."households" drop column "name";

alter table "public"."households" add column "title" text not null;

CREATE UNIQUE INDEX household_items_pkey ON public.household_items USING btree (id);

CREATE UNIQUE INDEX profiles_email_address_key ON public.profiles USING btree (email_address);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."household_items" add constraint "household_items_pkey" PRIMARY KEY using index "household_items_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."household_members" add constraint "household_members_member_id_fkey" FOREIGN KEY (member_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."household_members" validate constraint "household_members_member_id_fkey";

alter table "public"."profiles" add constraint "profiles_email_address_key" UNIQUE using index "profiles_email_address_key";

alter table "public"."household_items" add constraint "household_items_last_updated_by_fkey" FOREIGN KEY (last_updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."household_items" validate constraint "household_items_last_updated_by_fkey";

alter table "public"."households" add constraint "households_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."households" validate constraint "households_creator_id_fkey";


